---
- name: Configure host.
  hosts: localhost
  connection: local

  tasks:
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/casks.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/macos.yml
