---
- name: Configure host.
  hosts: localhost
  connection: local

  tasks:
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/casks.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/macos/dock.yml
    - import_tasks: tasks/macos/finder.yml
    - import_tasks: tasks/macos/appearance.yml
    - import_tasks: tasks/macos/language.yml
    - import_tasks: tasks/macos/wallpaper.yml
