---
- name: Add AeroSpace tap
  community.general.homebrew_tap:
    name: nikitabobko/tap

- name: Install alacritty
  community.general.homebrew_cask:
    name: alacritty
    state: present

- name: Install aerospace
  community.general.homebrew_cask:
    name: nikitabobko/tap/aerospace

- name: Install cryptomator
  community.general.homebrew_cask:
    name: cryptomator
    state: present

- name: Install enpass
  community.general.homebrew_cask:
    name: enpass
    state: present

- name: Install font-jetbrains-mono-nerd-font
  community.general.homebrew_cask:
    name: font-jetbrains-mono-nerd-font
    state: present

- name: Install karabiner-elements
  community.general.homebrew_cask:
    name: karabiner-elements
    state: present

- name: Install librewolf
  community.general.homebrew_cask:
    name: librewolf
    state: present

- name: Install obsidian
  community.general.homebrew_cask:
    name: obsidian
    state: present

- name: Install synology-drive
  community.general.homebrew_cask:
    name: synology-drive
    state: present

- name: Install thunderbird
  community.general.homebrew_cask:
    name: thunderbird
    state: present
