---
- name: Add AeroSpace tap
  community.general.homebrew_tap:
    name: nikitabobko/tap

- name: Install Alacritty
  community.general.homebrew_cask:
    name: alacritty
    state: present

- name: Install AeroSpace
  community.general.homebrew_cask:
    name: nikitabobko/tap/aerospace

- name: Install Cryptomator
  community.general.homebrew_cask:
    name: cryptomator
    state: present

- name: Install Discord
  community.general.homebrew_cask:
    name: discord
    state: present

- name: Install Elgato Wave Link
  community.general.homebrew_cask:
    name: elgato-wave-link
    state: present

- name: Install Enpass
  community.general.homebrew_cask:
    name: enpass
    state: present

- name: Install JetBrains Mono Nerd Font
  community.general.homebrew_cask:
    name: font-jetbrains-mono-nerd-font
    state: present

- name: Install Karabiner-Elements
  community.general.homebrew_cask:
    name: karabiner-elements
    state: present

- name: Install LibreWolf
  community.general.homebrew_cask:
    name: librewolf
    state: present

- name: Install Obsidian
  community.general.homebrew_cask:
    name: obsidian
    state: present

- name: Install Signal
  community.general.homebrew_cask:
    name: signal
    state: present

- name: Install Synology Drive
  community.general.homebrew_cask:
    name: synology-drive
    state: present

- name: Install Thunderbird
  community.general.homebrew_cask:
    name: thunderbird
    state: present
