---
- name: Install Homebrew packages
  community.general.homebrew:
    name:
      - neovim
      - ripgrep
      - fd
      - lua-language-server
      - python-lsp-server
      - opencode
      - openjdk
      - jdtls
      - stow
      - tmux
      - wget
      - wireguard-tools
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present
