---
- name: Enable dark mode
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: Dark

- name: Set sidebar icon size to medium
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: 2

- name: Set dark icon style
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleAquaColorVariant
    type: int
    value: 1
