- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

- name: Show all file extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: Show path bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

- name: Show status bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

- name: Disable extension change warning
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: Disable DS_Store on network drives
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Set list view as default in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv

- name: Restart Finder to apply changes
  ansible.builtin.command:
    cmd: killall Finder
