---
- name: Set computer name
  community.general.osx_defaults:
    domain: /Library/Preferences/SystemConfiguration/preferences
    key: ComputerName
    type: string
    value: overseer
  become: true

- name: Set host name
  ansible.builtin.hostname:
    name: overseer
  become: true

- name: Set local host name
  community.general.osx_defaults:
    domain: /Library/Preferences/SystemConfiguration/preferences
    key: LocalHostName
    type: string
    value: overseer
  become: true
